/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package katas;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        DailyCodingProblem20240730 classUnderTest = new DailyCodingProblem20240730();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
